name: Update Contributors
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update contributors
        run: python src/update_contributors.py

      - name: Commit and push files
        uses: EndBug/add-and-commit@v7
        with:
          push: "https://github.com/MatinGhanbari/v2ray-configs.git"
          message: "Update Contributors 🫂"
          author_email: "actions@github.com"
          author_name: "Github Actions"
          add: "public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
