name: Update V2Ray Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update V2Ray configs
        run: python src/update_v2ray.py

      - name: Update Warp configs
        run: python src/update_warp.py

      - name: Filter sub files
        run: python src/filter_subs.py

      - name: Update contributors
        run: python src/update_contributors.py

      - name: Commit Files
        run: |
          git config --local user.email "ghanbarimatin6@gmail.com"
          git config --local user.name "Matin Ghanbari"
          git add subscriptions
          git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
