name: Update V2Ray Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update V2Ray configs
        run: python src/update_v2ray.py

      - name: Update Warp configs
        run: python src/update_warp.py

      - name: Filter sub files
        run: python src/filter_subs.py

      - name: Update contributors
        run: python src/update_contributors.py

      - name: Commit Files
        run: |
          git config --local user.email "ghanbarimatin6@gmail.com"
          git config --local user.name "Matin Ghanbari"
          git add subscriptions
          git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"
      
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
      # - name: Clean Up Files
      #   run: |
      #     git checkout --orphan latest_branch
      #     git rm -r -f __pycache__ || true
      #     git config --local user.email "ghanbarimatin6@gmail.com"
      #     git config --local user.name "Matin Ghanbari"
      #     git add subscriptions
      #     git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"
      #     git branch -D main
      #     git branch -m main
      #     git push -f origin main

      # - name: Push Changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
          
      # - name: Commit and push changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"
      #     commit_user_name: GitHub Actions
      #     commit_user_email: actions@github.com
      #     commit_author: GitHub Actions <actions@github.com>
      #     file_pattern: "subscriptions/* public/assets/data/*"
      #     branch: main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
