name: Update V2Ray Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  update-configs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update V2Ray configs
      run: python src/update_configs.py
      
    - name: Update subscription files
      run: python src/generate_subscriptions.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🔄 Auto-update configs (15 min interval)"
        branch: main
        file_pattern: 'configs/* subscriptions/*'
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
        commit_author: GitHub Actions <actions@github.com>
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 